required_configuration:
	database:
		host: "localhost"
		database: "readie_dev"
		username: "sqluser"
		password: "sqluser"
	#These are the directorties that the website will be able to access, You must supply a name for the path, e.g. videos: "/home/readie/videos"
	paths:
		readie: "/home/readie"
optional_configuration:
	site:
		#This is the path that the website will be accessed from, e.g. http://localhost/<THIS_PART_OF_THE_URL>
		path: "/files"
		#This is the name that will appear in the browser's title bar.
		name: ""
	log:
		file: "/var/log/dedi-readie.global-gaming.co/files.log"
		level: 0